CREATE TABLE customers (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(100),
    member_status VARCHAR(20) DEFAULT 'NONE', -- NONE, BASIC, PREMIUM
    join_date DATE NOT NULL DEFAULT (CURRENT_DATE)
);